image: node:10

cache:
  paths:
  - TraBlockchain/ClientApp/node_modules

stages:
- deploy

pages:
  stage: deploy
  script:
    - cd TraBlockchain/ClientApp
    - npm config set '@bit:registry' https://node.bit.dev
    - npm install
    - CI=false npm run build
    - rm -rf public
    - cd ..
    - cd ..
    - mkdir public
    - cp -r -a  TraBlockchain/ClientApp/build/. public/
    - cd public
  artifacts:
    paths:
    - public
  only:
    - master
