image: node:10

cache:
  paths:
  - TraBlockchain/ClientApp/node_modules

stages:
- deploy

pages:
  stage: deploy
  script:
    - cd TraBlockchain/ClientApp
    - npm config set '@bit:registry' https://node.bit.dev
    - npm install
    - CI=false npm run build
    - rm -rf public
    - mkdir public
    - cp -r -a  build/. public/
    - cd public/static/js
    - dir
  artifacts:
    paths:
    - TraBlockchain/ClientApp/public
  only:
    - master
